### ISSUE TITLE
tar.gz missing

### ISSUE THREAD

**Issue by milkyklim** [holochain/dev-camp-tests-rust#2]
When I try to run `npm install` in the test folder I get an error

```
milkyklim | test (master) > npm install

> @holochain/holochain-nodejs@0.4.2-alpha install /Users/kkolyva/dev-camp-tests-rust/test/node_modules/@holochain/holochain-nodejs
> node-pre-gyp install || npm run fallback

node-pre-gyp WARN Using needle for node-pre-gyp https download
node-pre-gyp ERR! install error
node-pre-gyp ERR! stack Error: 404 status code downloading tarball https://github.com/holochain/holochain-rust/releases/download/holochain-nodejs-v0.4.2-alpha/index-v0.4.2-alpha-node-v59-darwin-x64.tar.gz
node-pre-gyp ERR! stack     at PassThrough.<anonymous> (/Users/kkolyva/dev-camp-tests-rust/test/node_modules/node-pre-gyp/lib/install.js:139:27)
node-pre-gyp ERR! stack     at PassThrough.emit (events.js:165:20)
node-pre-gyp ERR! stack     at ClientRequest.<anonymous> (/Users/kkolyva/dev-camp-tests-rust/test/node_modules/needle/lib/needle.js:482:9)
node-pre-gyp ERR! stack     at Object.onceWrapper (events.js:255:19)
node-pre-gyp ERR! stack     at ClientRequest.emit (events.js:160:13)
node-pre-gyp ERR! stack     at HTTPParser.parserOnIncomingClient [as onIncoming] (_http_client.js:548:21)
node-pre-gyp ERR! stack     at HTTPParser.parserOnHeadersComplete (_http_common.js:115:23)
node-pre-gyp ERR! stack     at TLSSocket.socketOnData (_http_client.js:439:20)
node-pre-gyp ERR! stack     at TLSSocket.emit (events.js:160:13)
node-pre-gyp ERR! stack     at addChunk (_stream_readable.js:269:12)
node-pre-gyp ERR! System Darwin 17.7.0
node-pre-gyp ERR! command "/usr/local/bin/node" "/Users/kkolyva/dev-camp-tests-rust/test/node_modules/.bin/node-pre-gyp" "install"
node-pre-gyp ERR! cwd /Users/kkolyva/dev-camp-tests-rust/test/node_modules/@holochain/holochain-nodejs
node-pre-gyp ERR! node -v v9.4.0
node-pre-gyp ERR! node-pre-gyp -v v0.11.0
node-pre-gyp ERR! not ok
404 status code downloading tarball https://github.com/holochain/holochain-rust/releases/download/holochain-nodejs-v0.4.2-alpha/index-v0.4.2-alpha-node-v59-darwin-x64.tar.gz
```

I've checked the releases https://github.com/holochain/holochain-rust/releases and index-v0.4.2-alpha-node-v59-darwin-x64.tar.gz is not there. 

Any quick way to fix this problem?

**Comment by Connoropolous** [comment]
Hey there!

Switch to nodejs version 8, 10, or 11, and that should resolve your issue.
